export const AppName = process.env.NEXT_PUBLIC_APP_NAME || "think impact";
export const AppDescription = process.env.NEXT_PUBLIC_APP_DESCRIPTION || "Generated by create next app";
export const AppURL = process.env.NEXT_PUBLIC_APP_URL || "http://thinkimpactjo.com";